### ISSUE TITLE
Switch maintenance of this crate

### ISSUE THREAD

**Issue by glebpom** [hmwill/tokio-linux-aio#32]
Hi,

Thanks for the great work on this crate. However, it's not much maintained and outdated at the time. I have mostly finished the huge refactoringwith support for tokio 0.2, and async/await, and with a few improvements on performance and stability. I'd like to continue maintaining it, and wondering, if it would be possible to pass the ownership of the `tokio-linux-aio` crate to me?

**Comment by aksatish19** [comment]
+1, thanks for writing this up and the great work on the crate.

@glebpom are you planning to release the tokio 0.2 and async/await refactor on this crate?

**Comment by glebpom** [comment]
@aksatish19 It's now in this repo: https://github.com/glebpom/linux-aio-tokio
I have released the first version but yanked it because there was a design issue leading to UB. I'll release a new one soon. Feel free the check and play with the code in the repo.

**Comment by glebpom** [comment]
I have just released it: https://crates.io/crates/linux-aio-tokio
